packages:
  - 'apps/*'
  - 'packages/*'

peerDependencyRules:
  allowedVersions:
    '@module-federation/metro>metro': '0.83.7'
    '@module-federation/metro>metro-config': '0.83.7'
    '@module-federation/metro>metro-file-map': '0.83.7'
    '@module-federation/metro>metro-resolver': '0.83.7'
    '@module-federation/metro>metro-source-map': '0.83.7'
    '@module-federation/metro-plugin-rock>@rock-js/tools': '0.14.1'

allowBuilds:
  nx: true

trustPolicyExclude:
  - fast-xml-parser@4.5.7

minimumReleaseAgeExclude:
  - '@oxfmt/binding-android-arm-eabi@0.59.0'
  - '@oxfmt/binding-android-arm64@0.59.0'
  - '@oxfmt/binding-darwin-arm64@0.59.0'
  - '@oxfmt/binding-darwin-x64@0.59.0'
  - '@oxfmt/binding-freebsd-x64@0.59.0'
  - '@oxfmt/binding-linux-arm-gnueabihf@0.59.0'
  - '@oxfmt/binding-linux-arm-musleabihf@0.59.0'
  - '@oxfmt/binding-linux-arm64-gnu@0.59.0'
  - '@oxfmt/binding-linux-arm64-musl@0.59.0'
  - '@oxfmt/binding-linux-ppc64-gnu@0.59.0'
  - '@oxfmt/binding-linux-riscv64-gnu@0.59.0'
  - '@oxfmt/binding-linux-riscv64-musl@0.59.0'
  - '@oxfmt/binding-linux-s390x-gnu@0.59.0'
  - '@oxfmt/binding-linux-x64-gnu@0.59.0'
  - '@oxfmt/binding-linux-x64-musl@0.59.0'
  - '@oxfmt/binding-openharmony-arm64@0.59.0'
  - '@oxfmt/binding-win32-arm64-msvc@0.59.0'
  - '@oxfmt/binding-win32-ia32-msvc@0.59.0'
  - '@oxfmt/binding-win32-x64-msvc@0.59.0'
  - '@oxlint/binding-android-arm-eabi@1.74.0'
  - '@oxlint/binding-android-arm64@1.74.0'
  - '@oxlint/binding-darwin-arm64@1.74.0'
  - '@oxlint/binding-darwin-x64@1.74.0'
  - '@oxlint/binding-freebsd-x64@1.74.0'
  - '@oxlint/binding-linux-arm-gnueabihf@1.74.0'
  - '@oxlint/binding-linux-arm-musleabihf@1.74.0'
  - '@oxlint/binding-linux-arm64-gnu@1.74.0'
  - '@oxlint/binding-linux-arm64-musl@1.74.0'
  - '@oxlint/binding-linux-ppc64-gnu@1.74.0'
  - '@oxlint/binding-linux-riscv64-gnu@1.74.0'
  - '@oxlint/binding-linux-riscv64-musl@1.74.0'
  - '@oxlint/binding-linux-s390x-gnu@1.74.0'
  - '@oxlint/binding-linux-x64-gnu@1.74.0'
  - '@oxlint/binding-linux-x64-musl@1.74.0'
  - '@oxlint/binding-openharmony-arm64@1.74.0'
  - '@oxlint/binding-win32-arm64-msvc@1.74.0'
  - '@oxlint/binding-win32-ia32-msvc@1.74.0'
  - '@oxlint/binding-win32-x64-msvc@1.74.0'
  - oxfmt@0.59.0
  - oxlint@1.74.0
  - '@module-federation/dts-plugin@2.8.0'
  - '@module-federation/error-codes@2.8.0'
  - '@module-federation/managers@2.8.0'
  - '@module-federation/metro-plugin-rock@2.8.0'
  - '@module-federation/metro@2.8.0'
  - '@module-federation/runtime-core@2.8.0'
  - '@module-federation/runtime@2.8.0'
  - '@module-federation/sdk@2.8.0'
  - '@module-federation/third-party-dts-extractor@2.8.0'
