import { StyleSheet } from 'react-native';

const colors = {
  accent: '#E8325C',
  accentPressed: '#C81E48',
  accentSoft: '#FFF0F3',
  hairline: '#DDDDDD',
  ink: '#222222',
  muted: '#6A6A6A',
  success: '#18794E',
  surface: '#FFFFFF',
} as const;

export const styles = StyleSheet.create({
  cartRow: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    flexDirection: 'row',
    marginBottom: 12,
    padding: 12,
  },
  checkout: {
    alignItems: 'center',
    backgroundColor: colors.accent,
    borderRadius: 12,
    justifyContent: 'center',
    marginTop: 16,
    minHeight: 52,
  },
  checkoutLabel: {
    color: colors.surface,
    fontSize: 15,
    fontWeight: '700',
    lineHeight: 21,
  },
  checkoutPressed: { backgroundColor: colors.accentPressed, opacity: 0.86 },
  content: {
    flexGrow: 1,
    paddingBottom: 32,
    paddingHorizontal: 20,
    paddingTop: 24,
  },
  delivery: {
    alignItems: 'center',
    backgroundColor: colors.accentSoft,
    borderRadius: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
    padding: 16,
  },
  deliveryBody: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: '500',
    lineHeight: 18,
    marginTop: 4,
  },
  deliveryTitle: {
    color: colors.ink,
    fontSize: 15,
    fontWeight: '700',
    lineHeight: 21,
  },
  empty: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.hairline,
    borderRadius: 16,
    borderWidth: 1,
    justifyContent: 'center',
    marginTop: 24,
    minHeight: 220,
    padding: 24,
  },
  emptyBody: {
    color: colors.muted,
    fontSize: 15,
    fontWeight: '500',
    lineHeight: 21,
    marginTop: 8,
    textAlign: 'center',
  },
  emptyTitle: {
    color: colors.ink,
    fontSize: 22,
    fontWeight: '700',
    lineHeight: 28,
  },
  free: {
    color: colors.success,
    fontSize: 15,
    fontWeight: '700',
    lineHeight: 21,
  },
  itemDetails: { flex: 1, paddingLeft: 12 },
  itemName: {
    color: colors.ink,
    fontSize: 17,
    fontWeight: '600',
    lineHeight: 22,
  },
  items: { marginTop: 20 },
  lineTotal: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 18,
    marginTop: 4,
  },
  pressed: { opacity: 0.6 },
  productArt: {
    alignItems: 'center',
    borderRadius: 12,
    height: 112,
    justifyContent: 'center',
    width: 104,
  },
  productMark: {
    color: colors.ink,
    fontSize: 22,
    fontWeight: '700',
    lineHeight: 28,
  },
  quantity: {
    color: colors.ink,
    fontSize: 15,
    fontWeight: '700',
    lineHeight: 21,
    minWidth: 32,
    textAlign: 'center',
  },
  stepButton: {
    alignItems: 'center',
    borderColor: colors.hairline,
    borderRadius: 12,
    borderWidth: 1,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  stepLabel: {
    color: colors.ink,
    fontSize: 22,
    fontWeight: '600',
    lineHeight: 28,
  },
  stepper: { alignItems: 'center', flexDirection: 'row', marginTop: 12 },
  subtitle: {
    color: colors.muted,
    fontSize: 15,
    fontWeight: '500',
    lineHeight: 21,
    marginTop: 8,
    paddingRight: 24,
  },
  success: {
    backgroundColor: colors.accentSoft,
    borderRadius: 16,
    marginTop: 12,
    padding: 16,
  },
  successBody: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: '500',
    lineHeight: 18,
    marginTop: 4,
  },
  successTitle: {
    color: colors.success,
    fontSize: 15,
    fontWeight: '700',
    lineHeight: 21,
  },
  summary: {
    backgroundColor: colors.surface,
    borderColor: colors.hairline,
    borderRadius: 16,
    borderWidth: 1,
    marginTop: 12,
    padding: 16,
  },
  summaryLabel: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: '500',
    lineHeight: 18,
  },
  summaryRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  summaryValue: {
    color: colors.ink,
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 18,
  },
  title: {
    color: colors.ink,
    fontSize: 32,
    fontWeight: '700',
    lineHeight: 38,
  },
  totalLabel: {
    color: colors.ink,
    fontSize: 17,
    fontWeight: '700',
    lineHeight: 22,
  },
  totalRow: {
    borderColor: colors.hairline,
    borderTopWidth: 1,
    marginBottom: 0,
    paddingTop: 12,
  },
  totalValue: {
    color: colors.ink,
    fontSize: 22,
    fontWeight: '700',
    lineHeight: 28,
  },
});
